import type { Metadata } from 'next'
import './globals.css'
import StoreProvider from './providers/StoreProvider'
import { LayoutWrapper } from '@/widgets/layout-wrapper'

export const metadata: Metadata = {
	title: 'Cyber List',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<StoreProvider>
			<html lang='en'>
				<LayoutWrapper>{children}</LayoutWrapper>
			</html>
		</StoreProvider>
	)
}
//flex-grow
